name: 'discord-scm-action'
description: 'GitHub action to upload build artifacts and messages to a Discord channel. '
author: 'ToppleTheNun'
inputs:
  discordWebhookId:
    description: 'The Discord webhook ID.'
    required: true
  discordWebhookToken:
    description: 'The Discord webhook token.'
    required: true
  artifacts:
    description: 'The path to the artifacts to upload.'
    default: ''
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ARTIFACTS: ${{ inputs.artifacts }}
    DISCORD_WEBHOOK_ID: ${{ inputs.discordWebhookId }}
    DISCORD_WEBHOOK_TOKEN: ${{ inputs.discordWebhookToken }}

