name: 'discord-scm-action'
description: 'GitHub action to upload build artifacts and messages to a Discord channel. '
author: 'ToppleTheNun'
inputs:
  discordWebhookId:
    description: 'The Discord webhook ID.'
    required: true
  discordWebhookToken:
    description: 'The Discord webhook token.'
    required: true
  artifacts:
    description: 'The path to the artifacts to upload.'
    default: ''
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
