name: 'discord-scm-action'
description: 'GitHub action to upload build artifacts and messages to a Discord channel. '
author: 'ToppleTheNun'
inputs:
  myInput:              # change this
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
